# Official docker compose image.
image:
  name: docker/compose:latest

variables:
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:dind


before_script:
  - apk add sed

  - docker version
  - docker-compose version
  - docker-compose up -d
  - docker-compose run --rm manager-php-cli composer install
  - docker-compose down
  - docker-compose up -d

stages:
  - test
  - deploy


testsJob:
  stage: test
  tags:
    - docker

  script:
    - docker-compose run --rm manager-php-cli vendor/bin/phpunit tests/Api/Ac --debug
    - docker-compose run --rm manager-php-cli vendor/bin/phpunit tests/Api/ServiceApiTest.php --debug


  only:
    - develop
    - master
